---
- name: Change Hostname
  hostname:
    name: "p01-nelson"

- name: Change /etc/hosts
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '\Debian\b'
    replace: "p01-nelson"

- name: Update Timezone
  timezone:
    name: "America/Recife"

- name: Update apt cache
  apt: update_cache=yes force_apt_get=yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Remove all unnecessary packages
  apt:
    autoremove: yes
    autoclean: yes
