---
- name: Main Playbook
  hosts: all
  become: yes
  tasks:

    - name: Configure System
      include_tasks: configure_system.yaml

    - name: Add Groups
      include_tasks: add_groups.yaml

    - name: Add Users
      include_tasks: add_users.yaml

    - name: Configure SSH
      include_tasks: configure_ssh.yaml

    - name: Authorize Keys
      include_tasks: authorized_keys.yaml

    - name: Configure LVM
      include_tasks: configure_lvm.yaml

    - name: Configure NFS
      include_tasks: configure_nfs.yaml

    - name: Access Monitoring
      include_tasks: access_log.yaml

